(function () {
	/**
	 * @class PMUI.event.MouseEvent
	 * @extend PMUI.event.Event
	 * Handles the events generated by the mouse
	 *
	 * @constructor
	 * Create a new instance
	 * @param {Object} options Constructor options
	 *
	 * @cfg {Object} element Defines the HTMLElement
	 * @cfg {Function} handler Defines the callback Function to be executed
	 * @cfg {PMUI.event.Action} action Defines an Action to be used to handle the callback
	 * @cfg {String} name Event name
	 */
	var MouseEvent = function (options) {
		MouseEvent.superclass.call(this, options);
	};

	PMUI.inheritFrom('PMUI.event.Event', MouseEvent);

	/**
	 * Defines the object's type
	 * @type {String}
	 */
	MouseEvent.prototype.type = "MouseEvent";

	/**
	 * Overwrites the listen function
	 * @param  {HTMLElement} el HTML element associated to the event
	 * @param  {String} event   Event name
	 * @param  {Function/PMUI.event.Action} handler Callback function or action object
	 */
	MouseEvent.prototype.listen = function (el, handler) {
		var handlerFunction;
		if (handler instanceof PMUI.event.Action){
			handlerFunction = handler.handler;
		} else {
			handlerFunction = handler;
		}
		jQuery(el).on(this.eventName, handlerFunction);
		this.setHandler(handlerFunction).setElement(el);
		return this;
	};

	PMUI.extendNamespace('PMUI.event.MouseEvent', MouseEvent);

	if (typeof exports !== 'undefined') {
		module.exports = MouseEvent;
	}

}());